name: .NET CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true                 # NuGet-Caching
          cache-dependency-path: |
            **/*.csproj
            **/packages.lock.json

      - name: Restore
        run: dotnet restore Blazor-Template.sln

      - name: Build (Release)
        run: dotnet build Blazor-Template.sln --configuration Release --no-restore

      - name: Test (mit Coverage)
        run: dotnet test Blazor-Template.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test-results.trx"

      # (Optional) Testresultate & Coverage als Artefakte anhängen
      - name: Collect Testresults
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
            **/TestResults/*/coverage.cobertura.xml
